# Generated by Django 2.1.5 on 2021-06-24 14:12

import django.core.validators
from django.db import migrations, models
import swimrecords.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwimRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('relay', models.BooleanField()),
                ('stroke', models.CharField(max_length=255, validators=[swimrecords.models.validate_stroke])),
                ('distance', models.IntegerField(validators=[django.core.validators.MinValueValidator(50, message='Ensure this value is greater than or equal to 50.')])),
                ('record_date', models.DateTimeField(validators=[swimrecords.models.validate_record_date])),
                ('record_broken_date', models.DateTimeField()),
            ],
        ),
    ]
