# Generated by Django 2.1.5 on 2021-06-24 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import swimrecords.models


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimrecord',
            name='record_broken_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='swimrecord',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 16, 45, 907160, tzinfo=utc), validators=[swimrecords.models.validate_record_date]),
        ),
    ]
